/*
 *  Copyright 2004 the mime4j project
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
/* Generated By:JJTree: Do not edit this line. /Users/jason/Projects/apache-mime4j-0.3/target/generated-sources/jjtree/com.broadcom.bt.util.mime4j/field/address/parser/AddressListParserTreeConstants.java */

package com.broadcom.bt.util.mime4j.field.address.parser;

public interface AddressListParserTreeConstants
{
  public int JJTVOID = 0;
  public int JJTADDRESS_LIST = 1;
  public int JJTADDRESS = 2;
  public int JJTMAILBOX = 3;
  public int JJTNAME_ADDR = 4;
  public int JJTGROUP_BODY = 5;
  public int JJTANGLE_ADDR = 6;
  public int JJTROUTE = 7;
  public int JJTPHRASE = 8;
  public int JJTADDR_SPEC = 9;
  public int JJTLOCAL_PART = 10;
  public int JJTDOMAIN = 11;


  public String[] jjtNodeName = {
    "void",
    "address_list",
    "address",
    "mailbox",
    "name_addr",
    "group_body",
    "angle_addr",
    "route",
    "phrase",
    "addr_spec",
    "local_part",
    "domain",
  };
}
