/*
 *  Copyright 2004 the mime4j project
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
/* Generated By:JJTree: Do not edit this line. /Users/jason/Projects/apache-mime4j-0.3/target/generated-sources/jjtree/com.broadcom.bt.util.mime4j/field/address/parser/AddressListParserVisitor.java */

package com.broadcom.bt.util.mime4j.field.address.parser;

public interface AddressListParserVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTaddress_list node, Object data);
  public Object visit(ASTaddress node, Object data);
  public Object visit(ASTmailbox node, Object data);
  public Object visit(ASTname_addr node, Object data);
  public Object visit(ASTgroup_body node, Object data);
  public Object visit(ASTangle_addr node, Object data);
  public Object visit(ASTroute node, Object data);
  public Object visit(ASTphrase node, Object data);
  public Object visit(ASTaddr_spec node, Object data);
  public Object visit(ASTlocal_part node, Object data);
  public Object visit(ASTdomain node, Object data);
}
