package com.aw.parrot;

public enum CtrStatusType {
	STATUS_INIT,
	YZS_MUSIC_PLAYING,
	YZS_MUSIC_STOP,
	YZS_MUSIC_PAUSE,
	DLNA_PLAY,
	DLNA_STOP,
	DLNA_PAUSE,
	BLUETOOTH_CONNECTED,
	BLUETOOTH_DISCONNECTED;
}
